### ISSUE TITLE
have problem to setting up the server

### ISSUE THREAD

**Issue by sealionking** [softescu/OpenStory#7]
have problem to setting up the server

any docker version?

**Comment by adrianpintilie** [comment]
Thank you for the interest. Not yet, however we will update the documentation soon!

Regards
OpenStory.

**Comment by sealionking** [comment]
thank you very much

**Comment by stanionut** [comment]
@sealionking please check the OpenStory Middleware which will help you connect your Drupal site with OpenStory
https://github.com/softescu/OpenStory-Middleware
